# Generated by Django 4.2.7 on 2026-04-14 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('r2_score', models.FloatField()),
                ('mean_squared_error', models.FloatField(blank=True, null=True)),
                ('mean_absolute_error', models.FloatField(blank=True, null=True)),
                ('training_samples', models.IntegerField(default=0)),
                ('test_samples', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Model Metric',
                'verbose_name_plural': 'Model Metrics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_order', models.BooleanField(default=False)),
                ('book_table', models.BooleanField(default=False)),
                ('votes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(max_length=100)),
                ('rest_type', models.CharField(max_length=100)),
                ('cuisines', models.CharField(max_length=200)),
                ('approx_cost', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('predicted_rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('model_used', models.CharField(default='RandomForest', max_length=50)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Restaurant Prediction',
                'verbose_name_plural': 'Restaurant Predictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
