# Generated by Django 4.2.7 on 2026-04-21 13:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(help_text='Upload audio file (WAV, MP3, FLAC, M4A, OGG)', upload_to='audio_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'mp3', 'flac', 'm4a', 'ogg'])])),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('duration', models.FloatField(blank=True, help_text='Audio duration in seconds', null=True)),
                ('mfcc_features', models.JSONField(blank=True, help_text='MFCC features extracted from audio', null=True)),
                ('zcr_features', models.JSONField(blank=True, help_text='Zero Crossing Rate features', null=True)),
                ('predicted_class', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Audio Classification',
                'verbose_name_plural': 'Audio Classifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('probability', models.FloatField()),
                ('audio_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='audio_classifier.audioclassification')),
            ],
            options={
                'verbose_name': 'Classification Result',
                'verbose_name_plural': 'Classification Results',
                'ordering': ['-probability'],
            },
        ),
    ]
