# Generated by Django 4.2.7 on 2026-04-20 03:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio_files/')),
                ('transcribed_text', models.TextField(blank=True, null=True)),
                ('word_count', models.IntegerField(default=0)),
                ('unique_words', models.IntegerField(default=0)),
                ('words_per_minute', models.FloatField(default=0.0)),
                ('audio_duration', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WordFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('frequency', models.IntegerField(default=0)),
                ('audio_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_frequencies', to='speech_analyzer.audioanalysis')),
            ],
            options={
                'ordering': ['-frequency', 'word'],
            },
        ),
    ]
