# Generated by Django 4.2.7 on 2026-04-22 03:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSegmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('ever_married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('age', models.IntegerField()),
                ('graduated', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('profession', models.CharField(choices=[('Healthcare', 'Healthcare'), ('Engineer', 'Engineer'), ('Lawyer', 'Lawyer'), ('Entertainment', 'Entertainment'), ('Artist', 'Artist'), ('Executive', 'Executive'), ('Doctor', 'Doctor'), ('Homemaker', 'Homemaker'), ('Marketing', 'Marketing')], max_length=20)),
                ('work_experience', models.FloatField(blank=True, null=True)),
                ('spending_score', models.CharField(choices=[('Low', 'Low'), ('Average', 'Average'), ('High', 'High')], max_length=10)),
                ('family_size', models.FloatField(blank=True, null=True)),
                ('var_1', models.CharField(blank=True, max_length=10, null=True)),
                ('predicted_segmentation', models.CharField(choices=[('A', 'Segment A'), ('B', 'Segment B'), ('C', 'Segment C'), ('D', 'Segment D')], max_length=1)),
                ('confidence_score', models.FloatField()),
                ('prediction_method', models.CharField(max_length=20)),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing_time', models.FloatField()),
            ],
            options={
                'verbose_name': 'Customer Segmentation',
                'verbose_name_plural': 'Customer Segmentations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('accuracy_score', models.FloatField()),
                ('training_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('parameters', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Model Performance',
                'verbose_name_plural': 'Model Performances',
                'ordering': ['-training_date'],
            },
        ),
    ]
