# Generated by Django 4.2.7 on 2026-04-19 04:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('audio_file', models.FileField(upload_to='audio_files/')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('sample_rate', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amplitude_envelope_avg', models.FloatField(blank=True, null=True)),
                ('zero_crossing_rate_avg', models.FloatField(blank=True, null=True)),
                ('rms_energy_avg', models.FloatField(blank=True, null=True)),
                ('spectral_centroid_avg', models.FloatField(blank=True, null=True)),
                ('spectral_bandwidth_avg', models.FloatField(blank=True, null=True)),
                ('spectral_rolloff_avg', models.FloatField(blank=True, null=True)),
                ('mfcc_features', models.JSONField(blank=True, null=True)),
                ('frame_size', models.IntegerField(default=1024)),
                ('hop_length', models.IntegerField(default=512)),
                ('audio_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio_app.audiofile')),
            ],
        ),
    ]
