# Generated by Django 4.2.7 on 2026-04-22 04:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_phrases', models.TextField(help_text='Comma-separated trigger phrases')),
                ('command_type', models.CharField(choices=[('wikipedia', 'Wikipedia Search'), ('web_open', 'Open Website'), ('time_query', 'Time Query'), ('greeting', 'Greeting'), ('unknown', 'Unknown Command'), ('error', 'Error')], max_length=20)),
                ('action_url', models.URLField(blank=True, help_text='URL to open for web commands')),
                ('description', models.TextField(help_text='Description of what this command does')),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Voice Command',
                'verbose_name_plural': 'Voice Commands',
                'ordering': ['command_type'],
            },
        ),
        migrations.CreateModel(
            name='VoiceInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_command', models.TextField(help_text='The voice command as spoken by user')),
                ('transcribed_text', models.TextField(help_text='Text transcribed from speech')),
                ('command_type', models.CharField(choices=[('wikipedia', 'Wikipedia Search'), ('web_open', 'Open Website'), ('time_query', 'Time Query'), ('greeting', 'Greeting'), ('unknown', 'Unknown Command'), ('error', 'Error')], default='unknown', max_length=20)),
                ('response_text', models.TextField(help_text="Assistant's response")),
                ('action_taken', models.TextField(blank=True, help_text='Action performed by assistant')),
                ('confidence_score', models.FloatField(blank=True, help_text='Speech recognition confidence', null=True)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_successful', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Voice Interaction',
                'verbose_name_plural': 'Voice Interactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
